export const database = [ /* "Banco de dados" de produtos comercializados no site */
    {
        codigoProduto:1,
        tituloProduto:"Jordan 4 Metalic Gold", 
        preco: 999.99, 
        descricao:"O Jordan 4 Metallic Gold é uma edição sofisticada do clássico Air Jordan 4, com detalhes dourados metálicos que adicionam luxo ao design. A parte superior é feita de couro branco de alta qualidade, proporcionando um visual clean e moderno. O dourado metálico aparece no logo Jumpman, na gola e na entressola. O tênis mantém o famoso sistema de amortecimento Air-Sole, garantindo conforto e suporte. Ideal para fãs da marca, ele oferece um estilo versátil para ocasiões casuais e sofisticadas. Uma edição limitada, desejada por colecionadores e entusiastas da moda.",
        imagemProduto: {
            img1:"images/Jordan 4 Metalic Gold.avif",
            img2:"images/Jordan 4 Metalic Gold - Sola.avif",
            img3:"images/Jordan 4 Metalic Gold - Direita.avif",
            img4:"images/Jordan 4 Metalic Gold - Cima.avif",
            img5:"images/Jordan 4 Metalic Gold - Lado.avif",
            img6:"images/Jordan 4 Metalic Gold - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:2,
        tituloProduto:"Jordan 4 Thunder", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Jordan 4 Thunder.avif",
            img2:"images/Jordan 4 Metalic Gold - Sola.avif",
            img3:"images/Jordan 4 Metalic Gold - Direita.avif",
            img4:"images/Jordan 4 Metalic Gold - Cima.avif",
            img5:"images/Jordan 4 Metalic Gold - Lado.avif",
            img6:"images/Jordan 4 Metalic Gold - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:3,
        tituloProduto:"Jordan 4 Went Cement", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Jordan 4 Went Cement.avif",
            img2:"images/Jordan 4 Went Cement - Sola.avif",
            img3:"images/Jordan 4 Went Cement - Direita.avif",
            img4:"images/Jordan 4 Went Cement - Cima.avif",
            img5:"images/Jordan 4 Went Cement - Lado.avif",
            img6:"images/Jordan 4 Went Cement - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:4,
        tituloProduto:"Dunk Low Malachite", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Dunk Low Malachite.avif",
            img2:"images/Dunk Low Malachite - Sola.avif",
            img3:"images/Dunk Low Malachite - Direita.avif",
            img4:"images/Dunk Low Malachite - Cima.avif",
            img5:"images/Dunk Low Malachite - Lado.avif",
            img6:"images/Dunk Low Malachite - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:5,
        tituloProduto:"Dunk Low Black Raspberry", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Dunk Low Black Raspberry.avif",
            img2:"images/Dunk Low Black Raspberry - Sola.avif",
            img3:"images/Dunk Low Black Raspberry - Direita.avif",
            img4:"images/Dunk Low Black Raspberry - Cima.avif",
            img5:"images/Dunk Low Black Raspberry - Lado.avif",
            img6:"images/Dunk Low Black Raspberry - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:6,
        tituloProduto:"Dunk Low Vintage Green", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Dunk Low Vintage Green.avif",
            img2:"images/Dunk Low Vintage Green - Sola.avif",
            img3:"images/Dunk Low Vintage Green - Direita.avif",
            img4:"images/Dunk Low Vintage Green - Cima.avif",
            img5:"images/Dunk Low Vintage Green - Lado.avif",
            img6:"images/Dunk Low Vintage Green - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:7,
        tituloProduto:"NOCTA Black", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/NOCTA Black.avif",
            img2:"images/NOCTA Black - Sola.avif",
            img3:"images/NOCTA Black - Direita.avif",
            img4:"images/NOCTA Black - Cima.avif",
            img5:"images/NOCTA Black - Lado.avif",
            img6:"images/NOCTA Black - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:8,
        tituloProduto:"Giannis Freak", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Giannis Freak.avif",
            img2:"images/Giannis Freak - Sola.avif",
            img3:"images/Giannis Freak - Direita.avif",
            img4:"images/Giannis Freak - Cima.avif",
            img5:"images/Giannis Freak - Lado.avif",
            img6:"images/Giannis Freak - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:9,
        tituloProduto:"Book 1 Haven", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Book 1 Haven.avif",
            img2:"images/Book 1 Haven - Sola.avif",
            img3:"images/Book 1 Haven - Direita.avif",
            img4:"images/Book 1 Haven - Cima.avif",
            img5:"images/Book 1 Haven - Lado.avif",
            img6:"images/Book 1 Haven - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
    {
        codigoProduto:10,
        tituloProduto:"Jordan 5 'El Grito'", 
        preco: 999.99, 
        descricao:"Te deixa muito mais bonito",
        imagemProduto: {
            img1:"images/Jordan 5 'El Grito'.avif",
            img2:"images/Jordan 5 'El Grito' - Sola.avif",
            img3:"images/Jordan 5 'El Grito' - Direita.avif",
            img4:"images/Jordan 5 'El Grito' - Cima.avif",
            img5:"images/Jordan 5 'El Grito' - Lado.avif",
            img6:"images/Jordan 5 'El Grito' - Costas.avif",
        },
        categoriaProduto: 'Sneakers',
        classificacaoProduto:"News",
        exibirHome: true
    },
]